# Generated by Django 5.2.6 on 2025-09-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=16)),
                ('b', models.CharField(max_length=16)),
                ('line', models.TextField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
