# Generated by Django 5.2.6 on 2025-09-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='b',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='move',
            old_name='a',
            new_name='start',
        ),
    ]
