# Generated by Django 5.2.6 on 2025-09-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_b_move_end_rename_a_move_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
