# Generated by Django 5.2.6 on 2025-09-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='san',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
