# Generated by Django 5.2.6 on 2025-09-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_line_san'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_white', models.BooleanField()),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
    ]
