# Generated by Django 5.2.6 on 2025-09-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='slug',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
    ]
