# Generated by Django 5.2.6 on 2025-09-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_line_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='type',
        ),
        migrations.AddField(
            model_name='move',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
    ]
