# Generated by Django 5.2.6 on 2025-09-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_move_type_move_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='line_inclusive',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
