# Generated by Django 5.2.6 on 2025-09-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_move_line_inclusive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
