# Generated by Django 5.2.6 on 2025-09-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_positions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Positions',
            new_name='Position',
        ),
    ]
