# Generated by Django 5.2.6 on 2025-09-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_positions_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Move',
        ),
    ]
